### ISSUE TITLE
2.0.6 is breaking things working on 2.0.5 ( error with read only and focusing )

### ISSUE THREAD

**Issue by StitiFatah** [Jungwoo-An/react-editor-js#198]
### Environment

- @editorjs/editorjs version: 2.24.3
- react-editor-js version: 2.0.6
- react 18.0.0
- next : 12.1.5
### Describe

Hi, 

as per the example naming ``` `editorCore.current.focus();``` throws `editorCore.current.focus is not a function`

and 

```editorCore.current.readOnly.toggle();``` throws `Cannot read properties of undefined (reading 'toggle')`

Both are working fine with 2.0.5 and **same React/NectJS and editorjs version**
