### ISSUE TITLE
Runtime Error: this._editorJS.destroy is not a function 

### ISSUE THREAD

**Issue by minhhieu1612** [Jungwoo-An/react-editor-js#190]
### Environment

- @editorjs/editorjs version: 2.23.2
- react-editor-js version: 2.0.6

### Describe
I currently using next.js version 12.1.4.
And the error occurs after the ClientEditorCore instance initial success as you can see below:
![image](https://user-images.githubusercontent.com/50686178/162167923-3b7085fa-3f4e-4fc5-9022-9a0d6a61c4ea.png)

Also, there are two editors components mount on the page:
![image](https://user-images.githubusercontent.com/50686178/162168881-bde3ca13-9143-4576-9f96-21f9d7c729c3.png)

Editor.tsx file:
`import React, { useEffect, useRef, useState } from "react";
import { EditorBlockPropsType } from "./index.type";
import { createReactEditorJS } from "react-editor-js";
import { ClientEditorCore } from "@react-editor-js/client/dist/client/src/client-editor-core";

const ReactEditorJS = createReactEditorJS();
const REACT_EDITOR_HOLDER_ID = "ssrHolder";

const EditorBlock = ({ content }: EditorBlockPropsType) => {
  let editorInstance;
  const [tools, setTools] = useState<any>();
  const initialValue = content || {
    time: 1635603431943,
    blocks: [
      {
        id: "sheNwCUP5A",
        type: "header",
        data: {
          text: "Editor.js",
          level: 2,
        },
      },
    ],
  };

  useEffect(() => {
    (async () => {
      const importedTools = await import("./editorTools");
      setTools(importedTools.EDITOR_JS_TOOLS);
    })();
    // console.log(EditorJS);
  }, []);

  if (!tools) {
    return <>Loading....</>;
  }

  return (
    <ReactEditorJS
      holder={REACT_EDITOR_HOLDER_ID}
      instanceRef={(instance: any) => (editorInstance = instance)}
      tools={tools}
      defaultValue={initialValue}
      placeholder="write something here..."
      onInitialize={(currentEditor: ClientEditorCore) =>
        console.log(currentEditor)
      }
    />
  );
};

export default EditorBlock;
`
editorTools.ts file:
`import Embed from "@editorjs/embed";
import Table from "@editorjs/table";
import List from "@editorjs/list";
import Warning from "@editorjs/warning";
import Code from "@editorjs/code";
import LinkTool from "@editorjs/link";
import Image from "@editorjs/image";
import Raw from "@editorjs/raw";
import Header from "@editorjs/header";
import Quote from "@editorjs/quote";
import Marker from "@editorjs/marker";
import CheckList from "@editorjs/checklist";
import Delimiter from "@editorjs/delimiter";
import InlineCode from "@editorjs/inline-code";
import SimpleImage from "@editorjs/simple-image";

export const EDITOR_JS_TOOLS = {
  embed: Embed,
  table: Table,
  marker: Marker,
  list: List,
  warning: Warning,
  code: Code,
  linkTool: LinkTool,
  image: Image,
  raw: Raw,
  header: Header,
  quote: Quote,
  checklist: CheckList,
  delimiter: Delimiter,
  inlineCode: InlineCode,
  simpleImage: SimpleImage,
};
`
My github repo: [](https://github.com/minhhieu1612/my-blogs)
Thank for support me,

**Comment by proteye** [comment]
I have the same error. Please fix it.

**Comment by Jungwoo-An** [comment]
I'm sorry for the late response. I'll fix it.

If you want to contribute this repo, feel free to create pull request.

**Comment by AdrianSchneider** [comment]
We just went through this as well: two components and a destroy error.

In our case, it was only broken in React 18. Downgrading to 17 fixed it for us.

**Comment by AlbinoGeek** [comment]
> We just went through this as well: two components and a destroy error.
> 
> In our case, it was only broken in React 18. Downgrading to 17 fixed it for us.

Incredible! This at least lets me try and develop with this.

**Comment by StitiFatah** [comment]
Are you guys sure it's A react version problem ? Just got this error with .focus after updating react-editor-js to 2.0.6 and downgrading to react-editor-js@2.0.3  solved it

**Comment by AlbinoGeek** [comment]
To be fair, this is not the only extension that explodes when you give it
react 18. One of the biggest changes, is the rendering mode. ReactDOM
absolutely floods the console telling you that render is deprecated, this
breaks a lot of extensions.

Pinning react and reactDOM 17 has worked great for me in the one
application I use this extension.

**Comment by lifedup** [comment]
I'm using React 18 and Next 12, and this plugin was duplicating the editor, and throwing destroy is not a function error. 

I fixed it by removing this plugin and using the default `editorjs`.

```
import EditorJS from "@editorjs/editorjs";
import { useEffect, useId, useRef } from "react";

const Editor = () => {
  const holder = useId();
  const editor = useRef<EditorJS | null>(null);

  useEffect(() => {
    if (!editor.current) {
      editor.current = new EditorJS({
        data: { blocks: [] },
        holder,
        tools: {},
      });
    }
    return () => {
      if (editor.current && editor.current.destroy) {
        editor.current.destroy();
      }
    };
  }, []);

  return <div id={holder}></div>;
};
```

If you use Next.js, you can dynamically import the component.

```
const Editor = dynamic(() => import("path/to/editor"), { ssr: false });
```

**Comment by bekogeko** [comment]
in next.js its giving an error about usage of useRef
![image](https://user-images.githubusercontent.com/53656966/173136897-c445a318-1c9e-4544-b069-99c7f4f84773.png)
second error is same

**Comment by bekogeko** [comment]
i realised its about strict mode and double invoking when its double invoked (its also means enviroment is in strict mode) its creates double instance and because of that one of them creates this error. Becase one of them is still null !!!

**Comment by tinwritescode** [comment]
Work for me:

```ts
const [tools, setTools] = useState<any>()

useEffect(() => {
  ;(async () => {
    const importedTools = await import('../components/editor-config')
    setTools(importedTools.EDITOR_JS_TOOLS)
  })()
}, [])

```

````ts
<EditorJs
  onInitialize={(editor: any) => {
    editorRef.current = editor
  }}
  placeholder="Notes"
  minHeight={100}
  onChange={(value: any) => {
    setFieldValue('note', value)
  }}
  tools={tools}
/>
````

**Comment by Avinash1721** [comment]
This issue is coming because with react 18 page is rendered twice. To avoid this, turn off the strict mode in next.config.js

https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode
https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state

**Comment by berkaygurbuz** [comment]
> I'm using React 18 and Next 12, and this plugin was duplicating the editor, and throwing destroy is not a function error.
> 
> I fixed it by removing this plugin and using the default `editorjs`.
> 
> ```
> import EditorJS from "@editorjs/editorjs";
> import { useEffect, useId, useRef } from "react";
> 
> const Editor = () => {
>   const holder = useId();
>   const editor = useRef<EditorJS | null>(null);
> 
>   useEffect(() => {
>     if (!editor.current) {
>       editor.current = new EditorJS({
>         data: { blocks: [] },
>         holder,
>         tools: {},
>       });
>     }
>     return () => {
>       if (editor.current && editor.current.destroy) {
>         editor.current.destroy();
>       }
>     };
>   }, []);
> 
>   return <div id={holder} ref={editor}></div>;
> };
> export default Editor;
> ```
> 
> If you use Next.js, you can import the component to work with SSR.
> 
> ```
> const Editor = dynamic(() => import("path/to/editor"), { ssr: false });
> ```

When I use your workaround, I couldn't write anything in input

**Comment by AlbinoGeek** [comment]
Not supporting react 18 will become less and less of an option as time goes
on. I understand that they are deprecating the virtual dom, frankly, good
riddance. You can also force a react 18 app to work with react 17, but when
react 19 comes around, that all goes out the window.

What doesn't make a whole lot of sense to me is that it's created twice and
react 18, that is the inverse of what I would expect the deprecation of
virtual dom to result in
